services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloud-storage'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=user'
    ports:
      - 5432:5432

  redis:
    image: 'redis:latest'
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6379
    ports:
      - 6379:6379