services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloud-storage'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=user'
    ports:
      - 5432:5432

  redis:
    image: 'redis:latest'
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6379
    ports:
      - 6379:6379

  minio:
    image: 'minio/minio:latest'
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: TestPassword123!
    command: server --console-address ":9001" /data