services:
  app:
    build:
      context: .
    container_name: cloud-file-storage
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .env
    ports:
      - 8080:8080

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data/

  redis:
    image: 'redis:latest'
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - ~/data/minio:/data